name: Build Matrix

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for (comma-separated: ubuntu-latest,windows-latest,macos-latest)'
        required: false
        default: 'ubuntu-latest,windows-latest,macos-latest'
        type: string
      skip_tests:
        description: 'Skip tests (for faster builds)'
        required: false
        default: false
        type: boolean

jobs:
  build-ubuntu:
    if: ${{ contains(github.event.inputs.platforms, 'ubuntu-latest') || github.event.inputs.platforms == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Set up virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run tests
        if: ${{ !github.event.inputs.skip_tests }}
        run: |
          export DISPLAY=:99
          uv run make test

      - name: Build executable
        run: |
          uv run python scripts/build_tray.py

      - name: List build artifacts
        run: |
          echo "Build artifacts:"
          find dist/ -type f -exec ls -la {} \; || echo "No dist directory found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu-latest
          path: |
            dist/
          retention-days: 7

  build-windows:
    if: ${{ contains(github.event.inputs.platforms, 'windows-latest') || github.event.inputs.platforms == '' }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          powershell -c "irm https://astral.sh/uv/install.ps1 | iex"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        if: ${{ !github.event.inputs.skip_tests }}
        run: |
          uv run make test

      - name: Build executable
        run: |
          uv run python scripts/build_tray.py

      - name: List build artifacts
        run: |
          echo "Build artifacts:"
          Get-ChildItem -Path dist\ -Recurse | Format-Table -AutoSize

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-latest
          path: |
            dist/
          retention-days: 7

  build-macos:
    if: ${{ contains(github.event.inputs.platforms, 'macos-latest') || github.event.inputs.platforms == '' }}
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        if: ${{ !github.event.inputs.skip_tests }}
        run: |
          uv run make test

      - name: Build executable
        run: |
          uv run python scripts/build_tray.py

      - name: List build artifacts
        run: |
          echo "Build artifacts:"
          find dist/ -type f -exec ls -la {} \; || echo "No dist directory found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-latest
          path: |
            dist/
          retention-days: 7
