name: Build Matrix

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for'
        required: false
        default: 'ubuntu-latest,windows-latest,macos-latest'
        type: string
      skip_tests:
        description: 'Skip tests (for faster builds)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(format('["{0}"]', join(split(github.event.inputs.platforms, ','), '","')) }}
        python-version: ['3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi

    - name: Install dependencies
      run: |
        uv sync

    - name: Set up virtual display (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Run tests
      if: ${{ !github.event.inputs.skip_tests }}
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          export DISPLAY=:99
        fi
        uv run make test

    - name: Build executable
      run: |
        uv run python scripts/build_tray.py

    - name: List build artifacts
      run: |
        echo "Build artifacts:"
        find dist/ -type f -exec ls -la {} \; || echo "No dist directory found"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          dist/
        retention-days: 7
